ArdentHQ/arkconnect-extension

src/shared/components/header/Header.tsx

Closes: https://app.clickup.com/t/86drpnjek

fix: keep addresses trigger active state when dropdown is open

---

src/components/wallet/TestnetLabel.tsx
src/shared/components/input/Checkbox.tsx
src/shared/components/input/RadioButton.tsx

https://app.clickup.com/t/86drk4r60
When tabbing into the Addresses dropdown and tabbing down the addresses, it would trigger an error for `primary600` when focusing on the Radio button. I believe this is from when I fixed the Firefox outline colour - https://app.clickup.com/t/86drkyb5h

fix: incorrect color references

---

src/lib/context/Profile.tsx

Closes https://app.clickup.com/t/86drqeye7

fix: set mainnet network as default when resetting profile

---

src/components/ledger/LedgerConnectionStep.tsx
src/components/steps/StepsNavigation.tsx
src/pages/ImportWithLedger.tsx

- Padding from steps navigation have been removed.
- It has been applied to the connect ledger 1st step instead.
- Connect ledger:
- Import address:

fix: import address padding

---

vite.config.ts

Closes https://app.clickup.com/t/86drrdyxd
After debugging the logs, I noticed that the issue was within the `vite-plugin-web-extension` code, specifically after making a call to this URL: `https://json.schemastore.org/chrome-manifest`. I assume the issue arises because that link is intermittently down.
By adding `skipManifestValidation`, we should be able to prevent this issue. As a side effect it seems that now is launching the browser earlier on dev mode which is nice. [See docs for details ->
](https://vite-plugin-web-extension.aklinker1.io/config/plugin-options.html#skipmanifestvalidation)

fix: skip manifest validation

---

src/css/general.css

- Based on current designs, the leading for each typeset has been specifically set instead of using a general percentage.

fix: adjust leading for each typeset

---

src/components/connections/ConnectionsList.tsx

- Disconnect icon is now red as in the designs.

fix: disconnect icon color

---

src/css/buttons.css

- Color for `yes` button in Disconnect modal has been fixed and is now red.
-

fix: color for 'yes' button in disconnect modal

---

src/shared/components/header/AddressesDropdown.tsx

- Address dropdown now closes on outside click.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/42afbbda-b297-4852-b22c-ef00040e87b0

fix: address dropdown closes on outside click

---

vitest.config.ts

For the time being only `src/lib/utils` should be included for coverage until we extend this

chore: only include utils in coverage

---

src/components/settings/SetupPassword.tsx
src/shared/components/loader/LoadingModal.tsx

- Margins in `Setup password` page have been updated.
- Background color for `Loading` pages on onboarding have been updated.
- Loading pages for transactions have also been fixed.

fix: onboarding page styles

---

src/shared/components/button/RowLayout.tsx

- Ark about copy icon has now been fixed and is positioned correctly.

fix: align about ark copy icon

---

src/pages/ImportWithLedger.tsx
src/shared/components/header/Header.tsx

- A new prop for header component has been added: `hideNavbar`. Which will render the alt version of our header if it is set as `True`.
- Navbar is now hidden in all the Ledger import pages.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/f0ca61cd-4a81-49ec-80ca-e6fcbf8f088d

fix: hide navbar on ledger pages

---

src/css/buttons.css
src/css/inputs.css
src/css/variables.css
tailwind.config.js

- Class names for toggle switch, radio, checkbox inputs have been grouped together. Same as the ones for passphrase, textarea and text inputs.
- New `shadow-green` custom color added to our palette.

refactor: group class names for inputs 

---

src/pages/ImportWithLedger.tsx

- Borders for error component have been fixed. Same as the height of its content and the paddings.
- Colors have been fixed to match the design.
- Light mode:
- Dark mode:

fix: ledger error component styling

---

src/components/steps/StepsNavigation.tsx
src/pages/ImportWithLedger.tsx

- Step navigation now supports `onClickBack` prop in case we want a custom action to happen when we click `back` button.
- If we click `back` on ledger selection page, we now re-run the checks for connection.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/d0498f22-55c8-4c71-a947-a9aebd64827e

refactor: recheck ledger list on clicking back button

---

src/components/ledger/ApproveWithLedger.tsx

The hooks need to be at the top level and they should be avoided inside conditions loops etc. https://legacy.reactjs.org/docs/hooks-rules.html#:~:text=Don't%20call%20Hooks%20inside,each%20time%20a%20component%20renders.
Spotted it while fixing build errors in https://github.com/ArdentHQ/arkconnect-extension/pull/184

fix: move ledger tx hooks outside of conditionals

---

src/components/approve/ActionBody.blocks.tsx
src/components/approve/ActionDetails.tsx
src/components/approve/ActionDetailsValue.tsx

- `ActionDetailsValue` component has been refactored. It now forwards the ref from the tooltips in case it is a child component.
- Tooltips are now being correctly rendered in Ledger approval pages.

fix: tooltips in Ledger approval page

---

src/components/ledger/ImportWallets.tsx

- Testnet icon is now displayed in select address header.
## Screenshots
- Mainnet:
- Testnet:

refactor: testnet icon in select Ledger address

---

src/components/connect/ErrorModal.tsx

- Modal title alignment has been fixed and it is now correctly centered.

fix: text alignment for modal title

---

src/components/approve/ActionBody.blocks.tsx
src/components/ledger/ImportWallets.tsx
src/components/wallet/ConnectedAddress.tsx
src/components/wallet/address/Address.blocks.tsx

- Styling for connection modal has been updated to match the designs.
## Screenshots
- Light mode:
- Dark mode:

refactor: connection modal styling

---

src/shared/components/input/Input.tsx

- `twMerge` is being removed from classnames in text inputs.

fix: remove twMerge from text input class names

---

src/components/connections/ConnectionLogoImage.tsx

- `color-thief-react` and other packages such as `react-color-extractor` were having CORS policy issues when trying to inspect the logo. This caused the image's backgrounds to go fully black on Firefox.
- Default styles have been set in case errors are returned when inspecting the favicon.
## Screenshots
- Light mode:
- Dark mode:

fix: default styles for connection logos on error

---

src/components/home/LatestTransactions.tsx
src/i18n/ns/pages.ts
src/pages/Home.tsx
src/shared/components/layout/Layout.tsx

- "Latest transactions" section has been added with the default placeholder for no transactions.

feat: latest transactions section

---

src/components/home/LatestTransactions.utils.tsx
src/components/transaction/Transaction.blocks.tsx
src/components/wallet/Amount.tsx

- `Amount` component has been refactored and now accepts `displayTooltip` property.
- Tooltip on details page will not be displayed anymore since it will always display the full value.

refactor: hide tooltip for details page

---

src/components/home/LatestTransactions.blocks.tsx

- Padding for `MULTI` badge has been added in the latest transactions section.

fix: add padding to multipayment badge

---

src/components/home/LatestTransactions.utils.tsx
src/components/transaction/details/TransactionBody.tsx
src/lib/hooks/useDelegateInfo.ts

- `useDelegateInfo` hook has been refactored and now also fetches the delegate address.
- We now display the delegate address instead of its public key on the transaction details page.

refactor: use delegate info to display delegate address

---

src/components/settings/others/AboutARK.tsx
src/i18n/ns/misc.ts

- Button with link for demo app has been added in `About ARK` page.

refactor: display demo app button

---

src/components/settings/SettingsMenu.tsx
src/shared/components/header/AddressesDropdown.tsx
tailwind.config.js

- New `dropdown-dark` shadow variable.
- `dropdown` variable for shadows has been adjusted to match the designs.
- Shadow for dropdowns in dark mode has been adjusted.
- Light mode: 
- Dark mode:

refactor: adjust dropdown shadow

---

src/components/transaction/details/TransactionBody.tsx

- Tooltip to display the full transaction id has been implemented in transaction details page.

refactor: display full transaction id in tooltip

---

src/components/home/LatestTransactions.utils.tsx

- A dash is now displayed in amount section for non-payment transactions.

refactor: display dash for non-payment transactions

---

src/pages/TransactionDetails.tsx

- We now display a spinner loader when the query to fetch the transaction details is loading.

feat: loading state for transaction details

---

src/components/wallet/Amount.tsx

- `Amount` component now takes consideration of signs when checking if the tooltip should be displayed or not.

fix: remove redundant amount tooltips

---

src/components/home/LatestTransactions.blocks.tsx

- The condition to render the skeleton loader now relies on having the delegate name property and not the object.

fix: skeleton loaders not appearing

---

src/components/transaction/details/TransactionBody.tsx

- Vote and Unvote positions in transaction details have been swapped to match designs.

refactor: swap vote and unvote positions in transaction details

---

src/components/home/LatestTransactions.blocks.tsx
src/components/transaction/Transaction.blocks.tsx
src/components/transaction/details/TransactionBody.tsx

- All addresses in latest transactions list and transaction details page have been refactored and now are trimmed to 10 characters, 5 per side.

refactor: trim address in transaction pages

---

src/components/home/LatestTransactions.blocks.tsx

- Outline in transaction list items in Firefox has been removed.

fix: remove outline for transaction list in firefox

---

src/components/home/LatestTransactions.blocks.tsx
src/components/home/LatestTransactions.tsx
src/components/home/TransactionButtons.tsx
src/pages/Home.tsx
src/pages/Receive.tsx
src/pages/Send.tsx
src/routing/index.ts

- `TransactionButtons` have been added back to the home page.
- Height for latest transactions list has been fixed.
- Basic structure for `Send` and `Receive` pages has been added.

refactor: re-enable send/receive buttons

---

src/components/home/LatestTransactions.blocks.tsx

- Dash has been refactored and is now a `span` to make sure it fully uses the css classnames set.

refactor: dash color in transaction items

---

src/components/home/LatestTransactions.utils.tsx
src/components/wallet/Amount.tsx

- `maxDecimals` to display in amounts has been set as 2.
- `< 0.01` will be displayed in case we have any amount with 3 or more decimals and is lower than `0.01`

refactor: handle transactions amounts

---

src/components/approve/ActionBody.tsx

- Vote/Unvote address is fully displayed in tooltip.

fix: display full vote/unvote address in tooltip

---

src/components/transaction/Transaction.blocks.tsx
src/components/transaction/details/TransactionBody.tsx

# [[tx details] move fiat value to right](https://app.clickup.com/t/86dtdkybm)
- Fiat values have been moved to the right.

refactor: move fiat value to right

---

src/components/transaction/details/TransactionBody.tsx

- Vote/Unvote delegate address is fully display in a tooltip when hovering it.

refactor: display delegate address on hover

---

src/components/home/LatestTransactions.blocks.tsx

- Delegate name is now displayed for resignation and registration-type transactions.

refactor: show delegate name for resignation/registration transactions

---

src/components/wallet/Amount.tsx

fixes the styling of small amounts ( < 0.01) so they no longer show as `+< 0.01` but `+ <0.01` instead

fix: improve small amount styling

---

src/pages/CreateContact.tsx

remainder for https://app.clickup.com/t/86dthe4rd + also adds max length validation
the reason the bindings error was thrown on a new profile, is due to `pnpm dev:bare` not having pre-seeded devnet wallets. The first wallet being added is a mainnet one, so validation based on the available profile coins would only work for mainnet as no devnet network exists yet.

fix: handle address validation issue for devnet

---

src/components/send/AddressDropdown.tsx

- We now focus on the input after the user selects a suggestions, preventing the display value to be shown unless we click outside of the address dropdown input.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/51649d0e-666e-4058-b05c-0a84e1938081

refactor: address dropdown behaviour

---

src/components/approve/ActionBody.blocks.tsx
src/components/approve/ActionBody.tsx
src/lib/hooks/useAddressBook.ts

- Contact name is now displayed on approval pages for transfer actions.
## Screenshots
- Transaction Approval page:
- Approved Transaction page:

refactor: display contact name on approval pages

---

src/pages/CreateContact.tsx
src/pages/EditContact.tsx

Fixes the address validation in `AddressBook` to identify given address's network and validate it against it.
For testing:
* Click on settings 3-dot menu
* Go to Address book
* Click on Add contact
* Enter an address either devnet or mainnet, and click save
* It should create the new address and properly assign the network indicator icon (`T` for devnet, and no icon for mainnet).

fix: validate address based on actual network

---

src/components/send/AddressDropdown.tsx
src/lib/hooks/useAddressBook.ts

- We now display the contacts filtered by the wallet's network on the address book dropdown.
-

refactor: display contacts per network

---

src/components/send/SendForm.tsx
src/pages/Send.tsx

- `Amount` input field is validated after clicking the `MAX` button.
- We now prevent this button to set a negative value if the fee exceeds the balance.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/26110667-a8cc-4bce-a68e-785bf0da8986

fix: max value button

---

src/components/send/SendForm.tsx

- We now display the tooltip with the total amount if the balance is above `0 ARK/DARK`.

refactor: display tooltip on send page if balance > 0

---

src/components/ledger/ApproveWithLedger.blocks.tsx

- `customFee` is now being passed as part of the state in `useSendTransferForm`. This will allow the custom fee to be considered in case it is passed.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/a2513f7a-6b92-4d52-999a-1e933a7aa5b7

fix: display correct transaction fee in approval pages

---

src/components/send/AddressDropdown.tsx

https://app.clickup.com/t/86dtkm86k

fix: avoid double scrollbars when address dropdown is open

---

src/components/send/AddressDropdown.tsx
src/components/send/SendForm.tsx
src/i18n/ns/error.ts
src/pages/Send.tsx

- An `isLoading` state has been added for address validation. This will prevent displaying errors while it is still loading. 
- Address dropdown hides the suggestions after pasting a 34-character long value.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/56a45665-12eb-41cd-89d9-65056f4b2693

refactor: hide suggestions after pasting address on send page

---

src/shared/components/input/Input.tsx

slightly moves the value up so it's in line with the input text

fix: center input placeholder placement

---

src/components/address-book/AddressBookList.tsx

- Copy button has been added to address book items.

refactor: display copy address button in address book

---

src/components/send/AddressDropdown.tsx

- Address book suggestions have been aligned correctly in Firefox.

fix: align address book suggestions

---

src/components/send/SendForm.tsx
src/pages/Send.tsx

- An specific width for the form has been set, preventing the form to resize when having errors.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/3e89004c-7104-480e-bf2e-59f0f0ba70e4

fix: form resizes on errors

---

src/pages/Approve.tsx
src/pages/Send.tsx

# [[address book] persist data on the approval page](https://app.clickup.com/t/86dtmeku7)
- We now persist data on approval page for transfers only.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/361c6539-8bd4-48b3-88e1-c791210dfb39

refactor: persist approval page

---

src/OneTimeEventHandlers.ts
src/lib/background/extension.wallet.ts
src/shared/components/header/AddressesDropdown.tsx

Closes https://app.clickup.com/t/86dtkphj3
Currently when the user changes the primary address, the extension emits the change event from the client side, which is error prone for cases where the user quickly closes the extension window before the change action finishes. 
This PR emits the change address event from the background in order to properly emit the event to active sessions even if the extension is closed.

fix: emit primary address change from background

---

src/pages/EditContact.tsx

- Edit form ignores the duplication check fi we're saving the same initial address.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/0dbb1152-4f83-4f92-b6f6-880bf5664b72

fix: ignore duplication check when saving same address

---

src/pages/SplashScreen.tsx

- Colors for splash screen in both the logo and the background have been updated.

fix: adjust colors for splash screen

---

src/components/settings/others/MultipleWalletLogout.tsx
src/css/buttons.css
src/i18n/ns/action.ts
src/pages/Logout.tsx
src/shared/components/button/Button.tsx

- Depends on #354 
- Button styles for `primary link button` have been updated.
- Text content for remove button has also been updated.
- New `secondaryLink` button variant.

fix: adjust button styles

---

src/components/approve/ActionBody.blocks.tsx
src/components/transaction/details/CopyTransactionId.tsx
src/components/transaction/details/TransactionBody.tsx

- New `CopyTransactionId` component.
- The button to copy the transaction id has been refactored, implementing new styles and a new copy on tooltip.

refactor: copy transaction id button

---

src/components/transaction/details/AmountBadge.tsx

- Amount badge with positive amounts will always be green, ignoring the chosen color palette.

refactor: make incoming amounts green

---

src/components/settings/SetupPassword.tsx

- Button placement for onboarding pages is now consistent.

fix: button placement consistency on onboarding pages

---

src/components/receive/QRActionButtons.tsx
src/components/receive/Recipient.tsx
src/components/wallet/CopyAddress.tsx

- Hover styles for buttons in `Receive` page have been updated.
- `CopyAddress` button has been refactored.
- Paddings for the recipient input have also been adjusted to match the design.

refactor: adjust styles for receive page buttons

---

src/components/wallet/CopyAddress.tsx
src/components/wallet/address/Address.blocks.tsx

- We now rely on `COPY_WITH_NAME` translation from i18n and capitalize the words in address tooltips to make them consistent.

refactor: make address tooltips consistent

---

src/components/wallet/AddressSettings.tsx
src/i18n/ns/pages.ts

- `i18n` has been implemented for address settings menu page.

refactor: implement i18n to address settings menu

---

src/components/vote/DelegatesList.tsx
src/pages/Vote.tsx

- Some padding has been added between the list and the button.

fix: adjust padding between list and button

---

src/components/vote/VoteFee.tsx
src/pages/Vote.tsx

- Padding has been added to the delegate list on vote page.
- Issue of scrollbars appearing in the fee section has been fixed.

fix: adjust vote fee styles

---

src/components/vote/VoteFee.tsx
src/pages/Vote.tsx

- Advanced fee input can now be edited as expected.

fix: allow editing in transaction fee

---

src/components/wallet/address/Address.blocks.tsx

- The cursor for change delegate has been changed from `pointer` to `default`.

fix: change delegate address cursor

---

src/components/approve/ApproveVote.tsx

- When errors are displayed while voting, the infinite loading loop will not appear anymore.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/25073bc2-e9d0-48c7-88aa-6c0e00fed677

fix: infinite loading loop on voting errors

---

src/components/connect/ErrorModal.tsx

- Max width has been set for error message and long words will now break.
## Screenshots:

fix: error message width and word break

---

src/i18n/ns/pages.ts
src/pages/Vote.tsx

- Missing `'Use the search to find other delegates'` text has been added at the bottom of the delegate list when the search query is empty.

refactor: add missing text in delegate list

---

src/lib/hooks/useDelegates.ts

- Resigned delegates are now being filtered.

fix: filter resigned delegates

---

src/constants.ts
src/pages/Send.tsx
src/pages/Vote.tsx

- We now validate that the' fee' is equal or lower than `1`.

fix: allow use of fast preset fee

---

src/components/approve/ActionBody.tsx

- Amount-type fields are now grouped in approval and approved pages.

refactor: group amount fields in action body

---

src/components/transaction/details/AmountBadge.tsx

- Colors used for amount badge have been updated to match the designs.

refactor: update amount badge styles

---

src/pages/VoteApproved.tsx

- Sender full address will now be displayed in the tooltip on approved transaction pages.

fix: display sender full address

---

src/components/approve/ActionBody.blocks.tsx
src/components/approve/ActionDetails.tsx

- `ActionDetailsRow` component has been refactored and now accepts custom class names.
- A tooltip is now displayed with the transaction ID.

refactor: display transaction

---

src/components/home/LatestTransactions.blocks.tsx

- The space between the header and the details in the latest transaction item has been increased by 2px.

refactor: adjust padding in latest transaction items

---

src/components/approve/RequestedSignatureMessage.tsx
src/components/ledger/ApproveWithLedger.blocks.tsx
src/components/ledger/ApproveWithLedger.tsx

- Paddings in Ledger signature approval page has been refactored to match the other screens.
- Additional refactor for `ApproveWithLedger` page.

refactor: ledger signature approval page

---

src/components/settings/others/AboutARK.tsx
src/constants.ts

- `GITHUB_RELEASES_URL` has been added to the constants file.
- A link to the release log for current version has been added to the `About` page.

refactor: add version link to release log

---

src/manifest.chrome.json
src/manifest.firefox.json

- A new shortcut has been added to both of our web manifest. The extension will now open using `Shift + Alt + A` on Windows and `Shift + Option + A` on Mac.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/cd26bd83-41fa-4187-b183-8f04245eed6e

feat: add shortcut to extension

---

src/lib/hooks/useResetExtension.ts
src/lib/store/ui/index.ts
src/lib/utils/localStorage.ts
src/pages/ForgotPassword.tsx
src/pages/Logout.tsx

- The theme color won't change when all the addresses are removed from the wallet.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/fdf7c7a1-7a15-4590-9783-af4ece3adb43

fix: prevent theme from changing when addresses are removed

---

src/components/settings/others/AboutARK.tsx

- Version link transition for Firefox has been fixed
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/36f37b22-2ac9-45c5-baa1-bfee7bd6571b

fix: version link firefox

---

src/components/send/UploadQRModal.tsx
src/pages/Send.tsx

- Logic and components to upload a QR have been moved to their own file.
The code in `Send` page has been refactored.

refactor: upload qr modal

---

src/components/send/SendForm.tsx
src/pages/Send.tsx

- Errors now persist on `Send` form when we close and open the extension again.
- A regex for the amount input has been set, this was causing issues with validation when typing letters or any non-number values.
https://github.com/user-attachments/assets/30319a60-b9aa-465e-8bd1-1be77a5f0790

refactor: persist errors on send form

---

src/shared/components/progress/ProgressBar.tsx
tailwind.config.js

- Progress bar from Onboarding page will now transition correctly on Firefox.
https://github.com/user-attachments/assets/e45564c7-3c62-450d-a3e9-156d9930b481

fix: progress bar transtion on firefox

---

src/components/send/SendModalButton.tsx
src/i18n/ns/pages.ts

- QR Upload button is now disabled on Firefox.
- A new tooltip will be displayed when hovering this disabled button.

refactor: disable qr upload button on firefox

---

src/components/connect/ErrorModal.tsx

- Styles for HTML inserted in error pages have been updated to prevent text being displayed horizontally.

fix: wallet already exists error page styles

---

src/manifest.chrome.json

Odd issue, but the extension stopped working on sites like https://demo.arkconnect.io/ and https://live.arkscan.io/ with the release of chrome v130, throwing in error in devtools regarding Content Security Policy and it not wanting to load the `content.js` file. After a lot of configuration adjustments it seems to work with this small change where the `content_scripts` gets changed from purely https to both https and http. 
Note that it only works when both are included. Having either https or http in itself will not allow the extension to work, but when the array contains both is magically works. The Firefox manifest remains as-is as it works fine there with just the https content scripts entry.

fix: resolve issue where extension would not load on sites
