src/components/connect/WalletCard.tsx
src/constants.ts
src/shared/components/button/RowLayout.tsx

Closes: https://app.clickup.com/t/86drqe8u7

chore: remove `SHORTER_CURRENCY_DIGITS_ALLOWED`

---

src/background.ts

Closes https://app.clickup.com/t/86drqju53

fix: set as not onboarded if reset

---

src/components/ledger/SignMessage.tsx
src/lib/utils/cropToMaxDigits.ts
src/lib/utils/formatCurrency.ts

Closes https://app.clickup.com/t/86drbnu2e

fix: default currency formatter locale to en-us if undefined

---

src/background.ts
src/lib/background/extension.ts
src/lib/background/extension.wallet.primary.ts
src/lib/background/handleAutoLock.ts

Closes https://app.clickup.com/t/86drqvu80

fix: persist profile data on extension restart

---

src/components/wallet/AddressSettings.tsx

Closes https://app.clickup.com/t/86drqw21y

fix: address settings overflow issue

---

.github/workflows/release.yml

so we have builds on `rc-*` branches as well

chore: include rc- branches in extension build

---

src/shared/components/button/RowLayout.tsx

closes [app.clickup.com/t/86drrb9tb](https://app.clickup.com/t/86drrb9tb)
cherry pick of https://github.com/ArdentHQ/arkconnect-extension/pull/64

fix: pointer cursor on about links

---

README.md
package.json
pnpm-lock.yaml
public/README.md
vite.production.config.ts

Closes https://app.clickup.com/t/86drrymgt

chore: remove unused `crypto-js` dependency

---

src/OneTimeEventHandlers.ts
src/background.ts
src/components/AutoUnlockWrapper.tsx
src/components/settings/SetupPassword.tsx
src/components/wallet/create/ConfirmPassphrase.tsx
src/components/wallet/create/index.tsx
src/lib/background/extension.ts

chore: fix build errors

---

src/css/inputs.css
src/shared/components/input/Input.tsx
src/shared/components/input/PasswordInput.tsx
tailwind.config.js

- Replaces #67
- `Input` component has been refactored and now uses tailwind.
- Custom class names have been created for its variants.
- Implementations of this component have also been updated.

refactor: tailwind for text inputs

---

src/shared/components/loader/LoadingModal.tsx

https://app.clickup.com/t/86drrz4ze

fix: loading screen background color

---

package.json
src/css/general.css
src/css/inputs.css
src/css/transitions.css
src/css/variables.css
src/main.css

Closes https://app.clickup.com/t/86drtfz6q

refactor: apply prettier to css files

---

src/components/connections/ConnectionsList.tsx
src/main.css

Closes https://app.clickup.com/t/86drr9yp3

fix: firefox outline color

---

src/main.css
src/shared/components/header/Header.tsx

https://app.clickup.com/t/86drtwjqm

fix: inputs focus outline issue

---

package.json
pnpm-lock.yaml
src/components/wallet/ConnectionStatus.tsx
src/components/wallet/CopyAddress.tsx
src/shared/components/header/AddressesDropdown.tsx
src/shared/components/header/Header.tsx
src/shared/components/header/HeaderButton.tsx
src/shared/components/header/HeaderWrapper.tsx
tailwind.config.js

Closes https://app.clickup.com/t/86drqmg1j

refactor: use tailwindcss on header

---

src/pages/Approve.tsx
src/shared/components/modal/Modal.tsx

- `Modal` component has been refactored and now implements tailwind.
- Its implementations have been updated.

refactor: modal component tailwind

---

src/main.css

Closes https://app.clickup.com/t/86drumpa9

fix: header z-index issue

---

src/shared/components/header/Header.tsx

https://app.clickup.com/t/86dru773f

fix: increase padding between icons

---

src/components/settings/others/AboutARK.tsx

- Cursor pointer has been added for all the button links in "About ARK" page.

fix: cursor pointer for about ark page links

---

src/components/connect/WalletCard.tsx
src/components/connections/ConnectionsList.tsx
src/components/wallet/AddressSettings.tsx
src/components/wallet/Amount.tsx
src/components/wallet/address/Address.blocks.tsx
src/shared/components/button/RowLayout.tsx

Closes: https://app.clickup.com/t/86drv1nw3
https://github.com/ArdentHQ/arkconnect-extension/assets/132887516/dcb05d62-d1b1-4700-bb9b-2d0dc69140b2

fix: add underline when hovering over address details

---

src/pages/SplashScreen.tsx
tailwind.config.js

- Custom class names for animations have been added.
- Splash screen has been refactored and now implements tailwind.

refactor: splash screen tailwind

---

src/pages/EnterPassword.tsx
src/shared/components/nav/InternalLink.tsx

- `InternalLink` component has been refactored.
- Password page has been refactored and now implements tailwind.
- Some minor tweaks to smeantic issues.

refactor: password page tailwind

---

src/components/connect/WalletCard.tsx

Closes https://app.clickup.com/t/86drv1nqa

fix: action card padding

---

src/css/buttons.css
src/css/inputs.css
src/css/variables.css
src/shared/components/button/BigButton.tsx
src/shared/components/button/RowLayout.tsx
src/shared/components/input/PassphraseInput.tsx
src/shared/components/input/Textarea.tsx
src/shared/components/modal/Modal.tsx
tailwind.config.js

- Box shadow, drop shadow and color palette have been updated.
- Implementations of these class names in tailwind have been refactored.

refactor: shadow and colors duplicate check

---

src/components/settings/SetupPassword.tsx

https://app.clickup.com/t/86drvv513

fix: accept terms spacing

---

src/components/wallet/ConnectedAddress.tsx

Closes: https://app.clickup.com/t/86drv1qpq

fix: connected modal style improvements

---

src/OneTimeEventHandlers.ts
src/lib/background/extension.ts
src/pages/Logout.tsx

Closes: https://app.clickup.com/t/86drw8c0p + fixes the same problem with extension reset
https://github.com/ArdentHQ/arkconnect-extension/assets/132887516/0f8a5526-589e-4381-a36e-d201db90ef1d

fix: missing setup password step

---

src/components/settings/others/AboutARK.tsx
src/shared/components/button/RowLayout.tsx

Closes https://app.clickup.com/t/86drvdu4x

refactor: update row layout to be used as a link

---

src/shared/components/input/PassphraseInput.tsx

Closes https://app.clickup.com/t/86drumkrh

fix: passphrase input styling

---

src/components/settings/SetupPassword.tsx

Closes https://app.clickup.com/t/86drwamwg

fix: adjust create password text color

---

src/OneTimeEventHandlers.ts

Closes: https://app.clickup.com/t/86drw9tdc

fix: set `hasOnboarded` flag when a wallet added

---

src/components/approve/ActionDetails.tsx
src/components/approve/RequestedTransactionBody.tsx
src/components/approve/RequestedVoteBody.tsx
src/components/approve/TransactionApprovedBody.tsx
src/components/approve/VoteApprovedBody.tsx

Closes https://app.clickup.com/t/86drkydvy

refactor: fiat value placement on action screens

---

src/components/connections/ConnectionLogoImage.tsx
src/components/connections/ConnectionsList.tsx
src/components/ledger/ApproveWithLedger.tsx
src/components/ledger/ImportWallets.tsx
src/components/ledger/Step.tsx
src/components/settings/SubPageLayout.tsx
src/components/settings/general/EditAddressName.tsx
src/components/steps/StepsNavigation.tsx
src/components/wallet/Amount.tsx
src/components/wallet/address/Address.blocks.tsx
src/components/wallet/create/GeneratePassphrase.tsx
src/pages/EnterPassword.tsx
src/pages/Onboarding.tsx
src/shared/components/handleStates/LoadingFullScreen.tsx
src/shared/components/header/AddressesDropdown.tsx
src/shared/components/layout/Layout.tsx
src/shared/components/progress/ProgressBar.tsx

https://app.clickup.com/t/86dt108zt

refactor: rename `classNames` to `cn`

---

src/lib/background/extension.ts
src/lib/utils/env.background.ts
src/lib/utils/localStorage.ts
src/lib/utils/migrations/move-onboarded-status-to-env.test.ts
src/lib/utils/migrations/move-onboarded-status-to-env.ts
vitest.setup.ts

refactor: add migration to move `hasOnboarded` flag to sdk env

---

src/components/ledger/ApproveWithLedger.tsx

- Styling for Ledger signature loader has been fixed.

fix: styling for signature loader

---

DOCUMENTATION.md
src/ArkConnectInPageProvider.ts

- Version from `package.json` is now exposed and can be accessed from `demo` using the following line:
```
window.arkconnect?.version()
```

refactor: expose version

---

src/pages/Home.tsx

- `TransactionButtons` component has been removed from `Home` page.

refactor: hide send/receive buttons

---

src/pages/Home.tsx

- Radius for balance card has been adjusted to match the designs.

refactor: adjust balance card radius

---

src/shared/components/header/AddressesDropdown.tsx

https://app.clickup.com/t/86dtd7bm4

fix: add custom scroll to addresses dropdown

---

.github/workflows/build.yml
.github/workflows/deps.yml
.github/workflows/format.yml
.github/workflows/release.yml
.github/workflows/test.yml
pnpm-lock.yaml

https://app.clickup.com/t/86dtcv2a6

chore: upgrade to pnpm v9

---

src/components/home/LatestTransactions.tsx

- Interval to fetch in latest transactions list has been updated and reduced to every 1 minute.

refactor: reduce fetching interval

---

src/components/home/LatestTransactions.blocks.tsx
src/components/transaction/details/TransactionBody.tsx
src/css/buttons.css
src/css/variables.css
tailwind.config.js

- Color palette and custom tailwind class names have been updated.
- Accessibility for transaction details pages has been added.
https://github.com/ArdentHQ/arkconnect-extension/assets/55117912/365e453b-d585-4523-83ba-1d987670db86

refactor: transactions accessibility

---

src/components/wallet/Amount.tsx

https://app.clickup.com/t/86dtfk1vm
oopsie

fix: undo change to force small amounts

---

package.json
pnpm-lock.yaml
vite.config.ts

https://app.clickup.com/t/86dtcv28x

fix: adjust config to work with vitest update

---

src/App.tsx
src/components/address-book/create/AddNewContactForm.tsx
src/dev/utils/dev.ts
src/lib/hooks/useResetExtension.ts
src/lib/utils/localStorage.ts
src/pages/CreateContact.tsx

- We now clear the address book when resetting the wallet.

fix: clear address book on resetting wallet

---

src/pages/CreateContact.tsx

initial styling changes for https://app.clickup.com/t/86dthe4rd

refactor: improve address validation naming

---

src/i18n/ns/pages.ts
src/pages/EditContact.tsx

- Message on toast alert when editing a contact has been updated.

refactor: modify message on edit contact

---

src/components/home/TransactionButtons.tsx
src/shared/components/button/Button.tsx

https://app.clickup.com/t/86dtkp2um

fix: increase icon in send and receive buttons

---

src/components/send/AddressDropdown.tsx
src/shared/components/input/Input.tsx

https://app.clickup.com/t/86dtk9jn0

refactor: improve address dropdown handling

---

src/pages/CreateContact.tsx
src/pages/EditContact.tsx

- We now ensure the contact addresses are unique.

refactor: ensure contact addresses are unique

---

src/pages/Send.tsx

- "Requested by" name has been replaced from `Arkconnect` to `ARK Connect` for internal calls.

fix: rename requested by call

---

src/pages/Send.tsx

https://app.clickup.com/t/86dtnnybz

fix: use proper bignumber comparison for amount

---

src/css/buttons.css

Closes https://app.clickup.com/t/86dtp2thc

refactor: adjust destructive disabled button colors

---

src/components/approve/ApproveBody.tsx
src/components/approve/ApproveFooter.tsx
src/components/approve/ApproveHeader.tsx
src/components/approve/ApproveLayout.tsx
src/components/approve/ApproveMessage.tsx
src/components/approve/ApproveTransaction.tsx
src/components/approve/ApproveVote.tsx
src/components/approve/RequestedSignatureMessage.tsx
src/components/connect/ConnectFooter.tsx
src/pages/Approve.tsx
src/pages/Connect.tsx
src/pages/TransactionApproved.tsx
src/pages/VoteApproved.tsx
src/shared/components/actions/ActionHeader.tsx
src/shared/components/actions/RequestedBy.tsx

- Action pages have been refactored, now only the body is scrollable, while the footer and header remain fixed.
- `ApproveLayout` has been created to apply the same structure for the different pages.
## Screenshots
- The following pages have been updated:
- Connection request
- Signature request
- Transaction request
- Vote request
- Transaction approved
- Vote approved

refactor: action pages scrolling

---

src/i18n/ns/action.ts
src/pages/Logout.tsx

https://app.clickup.com/t/86dtq7npj

refactor: remove obsolete cancel button on address removal page

---

src/pages/Send.tsx

https://app.clickup.com/t/86dtkm51h
Only changed one part which isn't a necessity but keeps things more aligned. Other places where fees are involved are the `ApproveTransaction` and `ApproveVote` components, but those already relied on bignumber when arithmetic was involved

refactor: use bignumber where relevant

---

src/components/settings/SettingsMenu.tsx
src/i18n/ns/pages.ts
src/pages/Vote.tsx
src/routing/index.ts

Closes https://app.clickup.com/t/86dtpy3u4

feat: add vote link and empty page

---

.github/workflows/build.yml
.github/workflows/deps.yml
.github/workflows/format.yml
.github/workflows/release.yml
.github/workflows/test.yml

- `pnpm/action-setup` has been updated from `v2` to `v4`.

chore: update pnpm/action-setup

---

src/lib/hooks/useDelegates.ts

Closes https://app.clickup.com/t/86dtr1cqb

fix: add delegates count limit 

---

src/lib/hooks/useDelegates.ts

- The current voted delegate is attached and displayed in the delegate list. This will prevent the bug when choosing a new delegate.

fix: display current voted delegate in delegate list

---

src/components/approve/ApproveTransaction.tsx
src/components/approve/CustomFeeAlerts.blocks.tsx

- Message for low fee has been lowercased.
- Low fee banner is now displayed in transaction approval pages.

refactor: low fee alerts

---

src/components/settings/others/AboutARK.tsx
src/constants.ts
src/lib/hooks/useOs.ts
src/pages/Onboarding.tsx
src/shared/components/icon/illustration/ShortcutIcon.tsx

- New `useOs` hook to get the operative system from the user.
- This hook has been implemented in multiple files.

refactor: use os hook

---

src/components/send/SendForm.tsx

https://app.clickup.com/t/86du326tq

fix: only apply fee regex on fee input

---

package.json
pnpm-lock.yaml
src/manifest.chrome.json

down the rabbit hole we went. 
references for future me:
- package fix for the issue: https://github.com/samrum/vite-plugin-web-extension/releases/tag/v5.1.1
- google member highlighting the issue: https://github.com/samrum/vite-plugin-web-extension/issues/144
- chrome issue tracker for this issue: [issues.chromium.org/issues/363027634](https://issues.chromium.org/issues/363027634)

fix: build failure on chrome 130+
